# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "26d1676c631796198dd8043a040ee0d4"
name = "sponsored-banners-app"
handle = "sponsored-banners-app"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = true

[build]
dev_store_url = "zrdstore7.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
